from pathlib import Path

from data_processor.core.pipeline import run_csv_pipeline


HEAVY_FIXTURE_PATH = Path("tests/fixtures/csv/real_world_messy_customers_heavy.csv")


def test_real_world_parser_detects_encoding_delimiter_and_header(
    tmp_path: Path,
) -> None:
    """
    Verify stable parser-level expectations for the heavy real-world CSV fixture.
    """
    output_path = tmp_path / "real_world_messy_customers_clean.csv"

    result = run_csv_pipeline(
        input_path=HEAVY_FIXTURE_PATH,
        output_path=output_path,
    )

    parse_diagnostics = result["diagnostic_bundle"]["parse_diagnostics"]
    detection = parse_diagnostics["detection"]

    assert output_path.exists()
    assert parse_diagnostics["encoding"] == "utf-8-sig"
    assert parse_diagnostics["delimiter"] == ";"
    assert parse_diagnostics["header_row_index"] == 4
    assert parse_diagnostics["preamble_row_count"] == 4
    assert detection["encoding"]["selected_encoding"] == "utf-8-sig"
    assert detection["delimiter"]["selected_delimiter"] == ";"
    assert "Header row was not the first source row." in parse_diagnostics["warnings"]


def test_real_world_parser_normalizes_duplicate_headers(
    tmp_path: Path,
) -> None:
    """
    Verify duplicate headers are detected and normalized into unique column names.
    """
    output_path = tmp_path / "real_world_messy_customers_clean.csv"

    result = run_csv_pipeline(
        input_path=HEAVY_FIXTURE_PATH,
        output_path=output_path,
    )

    table = result["table"]
    parse_diagnostics = result["diagnostic_bundle"]["parse_diagnostics"]

    assert table.schema.column_names() == [
        "customer_id",
        "name",
        "email",
        "email_2",
        "country",
        "amount",
        "signup_date",
        "active",
        "notes",
        "phone",
        "postal_code",
        "score",
    ]
    assert "email" in parse_diagnostics["duplicate_headers"]
    assert "One or more headers were duplicated." in parse_diagnostics["warnings"]


def test_real_world_parser_reports_row_shape_problems(
    tmp_path: Path,
) -> None:
    """
    Verify extra and missing fields are surfaced without exact brittle counts.
    """
    output_path = tmp_path / "real_world_messy_customers_clean.csv"

    result = run_csv_pipeline(
        input_path=HEAVY_FIXTURE_PATH,
        output_path=output_path,
    )

    parse_diagnostics = result["diagnostic_bundle"]["parse_diagnostics"]

    assert parse_diagnostics["rows_with_extra_fields"]
    assert parse_diagnostics["extra_field_count"] > 0
    assert parse_diagnostics["rows_with_missing_fields"]
    assert parse_diagnostics["missing_field_count"] > 0
    assert "One or more rows contain extra fields." in parse_diagnostics["warnings"]
    assert "One or more rows contain missing fields." in parse_diagnostics["warnings"]


def test_real_world_parser_preserves_metadata_rows_as_preamble(
    tmp_path: Path,
) -> None:
    """
    Verify metadata rows before the real header are preserved as preamble metadata.
    """
    output_path = tmp_path / "real_world_messy_customers_clean.csv"

    result = run_csv_pipeline(
        input_path=HEAVY_FIXTURE_PATH,
        output_path=output_path,
    )

    table = result["table"]
    preamble_rows = table.metadata["preamble_rows"]

    assert len(preamble_rows) == 4
    assert preamble_rows[0][0] == "CRM Export: Legacy customer migration"
    assert preamble_rows[1][0] == "Generated by: old_crm_v2"
    assert preamble_rows[2][0] == "Generated at: 2026-05-18 08:45:00"
    assert preamble_rows[3][0].startswith("Notes: mixed delimiters")
