from data_processor.adapters.csv_adapter import CsvAdapter
from data_processor.adapters.parse_diagnostics import ParseDiagnostics
from data_processor.reports.diagnostic_bundle import build_diagnostic_bundle


def test_parse_diagnostics_defaults_are_serializable() -> None:
    """
    Verify default parse diagnostics can be serialized.
    """
    diagnostics = ParseDiagnostics()

    result = diagnostics.to_dict()

    assert result["header_row_index"] == 0
    assert result["preamble_row_count"] == 0
    assert result["rows_with_extra_fields"] == []
    assert result["extra_field_count"] == 0
    assert result["rows_with_missing_fields"] == []
    assert result["missing_field_count"] == 0
    assert result["duplicate_headers"] == []
    assert result["empty_headers"] == []
    assert result["delimiter"] is None
    assert result["encoding"] is None
    assert result["warnings"] == []


def test_parse_diagnostics_records_extra_and_missing_fields() -> None:
    """
    Verify parser diagnostics count row width problems.
    """
    diagnostics = ParseDiagnostics()

    diagnostics.add_extra_fields(row_index=2, count=3)
    diagnostics.add_missing_fields(row_index=4, count=2)

    result = diagnostics.to_dict()

    assert result["rows_with_extra_fields"] == [2]
    assert result["extra_field_count"] == 3
    assert result["rows_with_missing_fields"] == [4]
    assert result["missing_field_count"] == 2


def test_csv_adapter_reports_extra_and_missing_fields(tmp_path) -> None:
    """
    Verify CSV parsing reports rows with too many or too few fields.
    """
    input_path = tmp_path / "short_extra_rows.csv"

    input_path.write_text(
        "customer_id,name,country\n"
        "1,Alice,Germany\n"
        "2,Bob\n"
        "3,Charlie,France,ignored\n",
        encoding="utf-8",
    )

    table = CsvAdapter(input_path).read()
    diagnostics = table.metadata["parse_diagnostics"]

    assert diagnostics["rows_with_missing_fields"] == [2]
    assert diagnostics["missing_field_count"] == 1
    assert diagnostics["rows_with_extra_fields"] == [3]
    assert diagnostics["extra_field_count"] == 1
    assert "One or more rows contain missing fields." in diagnostics["warnings"]
    assert "One or more rows contain extra fields." in diagnostics["warnings"]


def test_csv_adapter_reports_header_diagnostics(tmp_path) -> None:
    """
    Verify CSV parsing reports empty, duplicate, and shifted headers.
    """
    input_path = tmp_path / "header_diagnostics.csv"

    input_path.write_text(
        "Export generated by System X\n"
        "customer_id,name,name,\n"
        "1,Alice,Alicia,Germany\n",
        encoding="utf-8",
    )

    table = CsvAdapter(input_path).read()
    diagnostics = table.metadata["parse_diagnostics"]

    assert diagnostics["header_row_index"] == 1
    assert diagnostics["preamble_row_count"] == 1
    assert diagnostics["duplicate_headers"] == ["name"]
    assert diagnostics["empty_headers"] == [3]
    assert diagnostics["delimiter"] == ","
    assert diagnostics["encoding"] == "utf-8"
    assert "Header row was not the first source row." in diagnostics["warnings"]
    assert "One or more headers were duplicated." in diagnostics["warnings"]
    assert "One or more headers were empty." in diagnostics["warnings"]


def test_diagnostic_bundle_includes_parse_diagnostics(tmp_path) -> None:
    """
    Verify diagnostic bundle exposes parser diagnostics as a top-level section.
    """
    input_path = tmp_path / "bundle_parse_diagnostics.csv"

    input_path.write_text(
        "customer_id,name\n"
        "1,Alice\n"
        "2,Bob,Germany\n",
        encoding="utf-8",
    )

    table = CsvAdapter(input_path).read()
    bundle = build_diagnostic_bundle(table)

    assert "parse_diagnostics" in bundle
    assert bundle["parse_diagnostics"]["rows_with_extra_fields"] == [2]
    assert bundle["parse_diagnostics"]["extra_field_count"] == 1
